### ISSUE TITLE
Create the main menu

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#1]
Scene is located: project\ui\screens\main_menu\main_menu.tscn

Reference to the design doc:

<https://docs.google.com/document/d/12XMz55hPoiHIpLiMa2OahzhEeUOTiBL4aLBeNfbVLkA/edit?tab=t.0#heading=h.e88be343z4h5>

- [x] Create the background for the main menu
- [x] Create the buttons for the main menu
- [x] #4
- [x] #18

**Comment by ZacMonster1** [comment]
Test

**Comment by TheeVande** [comment]
test

**Comment by artsydye** [comment]
**artsydye**  has entered chat

**Comment by jonathandavidlewis** [comment]
@artsydye What do you think we break out into separate tasks so other people can help?
