### ISSUE TITLE
controls to be added/expanded upon

### ISSUE THREAD

**Issue by CruelRice** [Church-of-Crice/cationarytail#101]
Arrow keys / WASD - movement 

X - meow 

Space - further dialogue 

E - interacting

**Comment by shiser** [comment]
![Image](https://github.com/user-attachments/assets/4acba9b9-9dcc-46af-b5ed-8ccdf311c51a)
(also added arrow keys)

**Comment by shiser** [comment]
Final:
![Image](https://github.com/user-attachments/assets/e73d8983-b22d-495f-b649-af1d629f5a26)
Note: "Quit" button just intended as a quick temp usage for devs, not implemented yet anyway.

**Comment by shiser** [comment]
Upon introspection, we need

`act_pause:` _ESC, Start_

but that should be everything unless a new action type is added to the game
