### ISSUE TITLE
Control Lucretia in adoption center instead of player cat

### ISSUE THREAD

**Issue by CruelRice** [Church-of-Crice/cationarytail#103]
for the adoption center only.

- [ ] add collision around her sprite
- [ ] start scene with dialogue and Lucretia walking in ![Image](https://github.com/user-attachments/assets/be3b6885-3c93-4d7a-85f2-dba577f2c8a6)
- [ ] when all interactions are done, a pop up above the clerk appears (the red exclamation mark UI asset) 
- [ ] player can control walking up to the clerk on their own and interact with her, triggering losing control of her ![Image](https://github.com/user-attachments/assets/9fb4bda9-38e8-4729-aeeb-dd582bbcbe15)
- [ ] cut to character creation screen 
- [ ] cut to Lucretia at home, cat carrier in house

**Comment by jonathandavidlewis** [comment]
@Ben64 Is this something you are still working on? I wanted to get this finished, so I was going to do it, but I notice that it is assigned to you.

**Comment by Ben64** [comment]
Yep, gonna try to push it tonight
