### ISSUE TITLE
create a sprite and character portrait for death

### ISSUE THREAD

**Issue by CruelRice** [Church-of-Crice/cationarytail#109]
mikis concept art for inspiration 

![Image](https://github.com/user-attachments/assets/98e11185-8af2-4bd8-b54a-706acb2bc5bf)

portrait dimensions: 64 x 64

sprite dimensions: ???

**Comment by sigil-snoot** [comment]
I can start this.

**Comment by sigil-snoot** [comment]
![Image](https://github.com/user-attachments/assets/464c9fcb-681c-4c1e-98d2-b6d05a92f9e2)
![Image](https://github.com/user-attachments/assets/a8133a41-8767-4834-a94f-318778f3093c)
