### ISSUE TITLE
When the player dies, they respawn at the vet

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#20]
Depends on the vet location 

- [ ] #5 
- [ ] Ensure death mechanic
- [ ] Add respawn mechanic

**Comment by DeadRobotDev** [comment]
I'd be down for tackling this.

I see there is a separate issue for the global death tracking. Am I interacting with the global death tracking at all? Or am I simply exposing a function that respawns the player at a location?

Thanks!

**Comment by jonathandavidlewis** [comment]
@DeadRobotDev First, you'll need to layout the scenes in a single space, then you can just do the location spawning. The vet can have a marker and player dies, player can teleport to that location, yeah.

**Comment by DeadRobotDev** [comment]
By layout scenes in a single space, are you talking having them all in `world_map`?
Or a root scene, purely for allowing teleports between scenes?
If the latter, can I also use a singleton / autoload?

**Comment by jonathandavidlewis** [comment]
@DeadRobotDev I think we are going to want a persistent scene that has both the WOLRD area and the INSIDE buildings.

Does this image clarify?

![image](https://github.com/user-attachments/assets/c0d7f605-335c-4762-b38a-ab2ad14f5d6c)

**Comment by jonathandavidlewis** [comment]
This represents what would happen on death

![image](https://github.com/user-attachments/assets/11c41b77-501f-4eb8-834a-7d077eee118e)

**Comment by DeadRobotDev** [comment]
Yeah, I think so. So a separate scene that has all the other scenes placed in it, including `world_map`.
- Add this to Autoload.
- Add a function, like `respawn` that teleports the player to the vet?

Am I correct that this doesn't include `story_scenes`?

**Comment by jonathandavidlewis** [comment]
This `game_world` scenewould be loaded in scene_manager` global, but doesnt need to be its own global (I think)
The game world as seen here doesn't need to be instantiated until the player first walks into the world map after scene 4.

Yeah, these don't need the story scenes. Those are basically one-offs that USE locations within them.

 function `respawn` is great.
 
 You may want that in a global, not positive. go for it.

Having the whole "game_world" be a constant global may be an ez way to go.
