### ISSUE TITLE
Create the asset art for trees

### ISSUE THREAD

**Issue by sigil-snoot** [Church-of-Crice/cationarytail#25]
Create assets for trees. Need at least 2, one with a general rounded shape like a maple or oak, one with a general triangular shape like a conifer. 

Must be cohesive with other environmental assets, particularly with the grass tiles of outdoor settings. 
Must fit on screen in outdoor environments and be significantly taller than the character art. 
Proposed template size: 50 x 80 px.

**Comment by sigil-snoot** [comment]
![maple-tree](https://github.com/user-attachments/assets/0e10c084-24dc-448f-8096-afc2ed3fe8eb)
![pinee-tree](https://github.com/user-attachments/assets/f4657a27-5a57-419f-b645-0f58d44e0031)

**Comment by jonathandavidlewis** [comment]
@sigil-snoot are those assets to be integrated? or just ideas? I can grab them and commit them if they are intended to be used.

**Comment by jonathandavidlewis** [comment]
@sigil-snoot Nice work on this ticket.

**Comment by sigil-snoot** [comment]
@jonathandavidlewis yea those are intended to be used. We may make more later but I think we said 2 was the minimum for MVP.

**Comment by jonathandavidlewis** [comment]
TY!
