### ISSUE TITLE
Create art for shelter clerk

### ISSUE THREAD

**Issue by sigil-snoot** [Church-of-Crice/cationarytail#26]
Detailed design: bust-up highly detailed portrait, must fit in dialogue scenes. 
suggested template size: 64 x 64 px
- [x] Create details portrait for the Shelter Clerk

World sprite design: full body low detail model, depending on scene, may require walking animation
suggested template size: 64 x 32 px
- [x] Create world sprite for the Shelter Clerk

**Comment by sigil-snoot** [comment]
![shelter_clerk2](https://github.com/user-attachments/assets/77048306-fde1-44f9-b763-571697f0321d)

**Comment by jonathandavidlewis** [comment]
@sigil-snoot Nice work making this issue and providing the concept art! 🚀

**Comment by sigil-snoot** [comment]
1st draft of dialogue sprite, working with art team to make sure we all like it
![shelter_clerk](https://github.com/user-attachments/assets/0d58ff4b-3b93-44cc-9a79-9e5a4ee506c0)

**Comment by sigil-snoot** [comment]
notes from team: Darken contours

**Comment by sigil-snoot** [comment]
![shelter_clerk](https://github.com/user-attachments/assets/efb453b8-d4c0-4a67-8b1f-37dd03c2cd7b)

**Comment by sigil-snoot** [comment]
![shelter_clerk_world](https://github.com/user-attachments/assets/639936bd-aaca-4d35-b455-4221ed093411)

**Comment by sigil-snoot** [comment]
Going to add hair highlights to world sprite and make head a bit smaller.

**Comment by sigil-snoot** [comment]
![shelter_clerk](https://github.com/user-attachments/assets/48073cee-c0b0-4a8d-b4e4-875e31b3a1fb)
