### ISSUE TITLE
Complete story and dialog for the trip to the vet

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#3]
Existing scene and dialog:
<https://docs.google.com/document/d/12XMz55hPoiHIpLiMa2OahzhEeUOTiBL4aLBeNfbVLkA/edit?tab=t.wimkihulvbsf#heading=h.jbd8almxk5nk>

**Comment by ZacMonster1** [comment]
am Zac

**Comment by drsquawkol** [comment]
Test.

**Comment by jonathandavidlewis** [comment]
Hey, I think we need to add the dialog where the owner gets angry, right?
