### ISSUE TITLE
Create a walk animation for each type of cat body

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#31]
The head and neck will need to remain stationary for the static overlays of the collar and eyes to function without changes.

- [ ] Create a walk animation for the black cat body
- [ ] Create a walk animation for the brown cat body
- [ ] Create a walk animation for the calico cat body
- [ ] Create a walk animation for the grey with white cat body
- [ ] Create a walk animation for the orange cat body
- [ ] Create a walk animation for the Russian blue cat body
- [ ] Create a walk animation for the Siamese cat body
- [ ] Create a walk animation for the white cat body

You can upload the Aseprite file here: https://github.com/Church-of-Crice/cationarytail/upload/main/project/characters/player_character/art

**Comment by jonathandavidlewis** [comment]
@CruelRice Are you going to take this one?

**Comment by jonathandavidlewis** [comment]
@CruelRice Do you happen to be using Aseprite?

**Comment by CruelRice** [comment]
@jonathandavidlewis yes

**Comment by jonathandavidlewis** [comment]
NICE! You can just provide the aseprite file if its just the car with something like a layer per color of cat.

**Comment by jonathandavidlewis** [comment]
@CruelRice Can you also upload the aseprite file with the cat to the same location? It might be easier to export the cat animations differently. I don't mind exporting.

**Comment by jonathandavidlewis** [comment]
Specifically as a sprite sheet Or it can be done automaticaly from an aseprite file in Godot.
