### ISSUE TITLE
Create thought bubble mechanic

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#36]
A thought bubble appears with either an image or icon in it based on some area of proximity to something that is deadly.

- Only when the player has not already died to this thing.
- Pop up occassionally while in the area.
- Show for about 5 seconds.
- don't show for 10 seconds.

make exports for the time its visible, the time its not visible.

Also, make an Area2D that interacts with these thought bubbles.

make an export for the thought bubble or player. (or maybe select by group)

Some of the relevant concepts for this one:

![image](https://github.com/user-attachments/assets/7166d664-9180-492c-ac90-10337fa2d08b)

**Comment by jonathandavidlewis** [comment]
@SuddenLeeus @TheRealDude-x 
As far as I understand, there is no significant work on this, so I'm going to make a system for this shortly.
Please let me know if you already have something functional. TY!

**Comment by SuddenLeeus** [comment]
Yeah, I couldn't get anything useful working with the time I had, sorry sensei !

**Comment by jonathandavidlewis** [comment]
@SuddenLeeus No problem! I had fun. lol
