### ISSUE TITLE
Add sounds for main menu button interactions.

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#4]

**Comment by ZacMonster1** [comment]
I will be working on some options for these

**Comment by ZacMonster1** [comment]
Cannot upload MP3s here, but Lisa said she liked the [one linked for button sound](https://discord.com/channels/767866932967637052/1295476766403727460/1296247330093137971)

**Comment by ZacMonster1** [comment]
Sound file located [here](https://discord.com/channels/767866932967637052/1295476766403727460/1296633284498821120)
