### ISSUE TITLE
Create a dialog system

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#41]
Should work to display dialog via a global.
Takes player input like ENTER to move to the next part of the dialog.

- [x] #46

**Comment by jonathandavidlewis** [comment]
@SplaudPanther
I'm Working on the resizable border components which are a subtask here.
Shouldn't conflict with anything.

**Comment by splaudpanther** [comment]
Not sure if this is what we are looking for in regards to a dialog systems, but feel to make any tweak or suggestions, I am very very new to this lol
