### ISSUE TITLE
Create art for the Trip to the vet scene

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#5]
## Environment Art

Probably desaturated, greyish-blue, grossly clinical, a visual mix of a mad scientist's laboratory and a typical doctor's office, dark lighting and relatively high tech.

- [ ] Create the environment art for the Vet Office

## Reference Images

![image](https://github.com/user-attachments/assets/2c0517d0-1a2b-42d2-ae4a-26b57137ac51)

**Comment by drsquawkol** [comment]
This works for me!

**Comment by jonathandavidlewis** [comment]
- [ ] Create the vet sprite
- [ ] Create the cat carrier.

**Comment by jonathandavidlewis** [comment]
@drsquawkol Do you want to break out the task for creating the environment art for the vet into a different task? If we do, do you want that task also?

**Comment by shiser** [comment]
done for now
