### ISSUE TITLE
Fix y-sort on player and tiles in the shelter scene

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#69]
- [ ] ![Image](https://github.com/user-attachments/assets/d2c57f84-df16-4755-bead-3085a179841d) close this gap by counter

**Comment by CruelRice** [comment]
collision border for walls should be cut down by half.

**Comment by CruelRice** [comment]
collision on counter needs to be expanded by one pixel on the left.

**Comment by shiser** [comment]
Donezo!
