### ISSUE TITLE
Create the environment art for the Cat Gets adopted scene.

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#7]
Animal Rescue 

A cute setting with other adoptable animals that can be interacted with. The character can only pick our Cat. The Rescue has a clerk working behind a counter who helps us adopt our cat. 

There's a Waiting area…

There's a Back area…

## Reference images:

![image](https://github.com/user-attachments/assets/7ef90f92-5b72-4584-b568-50b25a56e6d0)

![image](https://github.com/user-attachments/assets/cf56419c-7523-44ef-aa21-83f0c4f009b0)

Link to the locations in Game Design Document:
<https://docs.google.com/document/d/12XMz55hPoiHIpLiMa2OahzhEeUOTiBL4aLBeNfbVLkA/edit?tab=t.0#heading=h.iqcqdos89sms>

**Comment by artsydye** [comment]
Here 👋
