### ISSUE TITLE
Create the Story and dialog for the Cat Gets Adopted Scene

### ISSUE THREAD

**Issue by jonathandavidlewis** [Church-of-Crice/cationarytail#9]
## Link to existing planning doc:
<https://docs.google.com/document/d/12XMz55hPoiHIpLiMa2OahzhEeUOTiBL4aLBeNfbVLkA/edit?tab=t.ien31ws9ssj5#heading=h.a5mrlbp2biet>

**Comment by jonathandavidlewis** [comment]
@ZacMonster1

**Comment by jonathandavidlewis** [comment]
# Example scene format

Scene: An animal adoption center filled with various animals in their enclosures. The player controls the human, moving around to interact with each animal.

**[Music: Light, cheerful tune playing in the background]**

*The player moves the human towards a scruffy-looking dog.*

**Human:**
"Hey there, buddy! You look like you could use a friend."

**Dog (snarky remark):**
"Yeah, well, as long as you don't mind sharing your bed. I snore. Loudly."

*The player moves the human to a parrot in a large cage.*

**Human:**
"Oh, what a beautiful bird! Would you like to come home with me?"

**Parrot (snarky remark):**
"Depends. Do you like waking up at 5 AM to me screaming for no reason?"

*The player moves the human to a fluffy white rabbit.*

**Human:**
"Aw, you're so cute and fluffy! I bet you'd be a great cuddle buddy."

**Rabbit (snarky remark):**
"Sure, if by cuddling you mean chewing all your expensive cables while you sleep."

*The player finally moves the human to a female black cat lounging in her enclosure.*

**Human:**
"Oh, look at you, so elegant and mysterious. How about you come home with me?"

**Cat (snarky remark):**
"Take me home, human, but don't expect me to be impressed by anything you do."

**Human (chuckling):**
"I think you're perfect. Let's get you out of here."

*The screen fades out as the human fills out the adoption paperwork and leaves the center with the black cat.*

**[End Scene]**

**Comment by ZacMonster1** [comment]
[This has been completed](https://docs.google.com/document/d/12XMz55hPoiHIpLiMa2OahzhEeUOTiBL4aLBeNfbVLkA/edit?tab=t.ien31ws9ssj5)

**Comment by jonathandavidlewis** [comment]
Scene Sequence
	> = Scene Action
	[] = Dialogue
	{} = Thoughts

> Owner walks into the shelter. The Clerk is sitting at her desk scrolling on her phone.

[Owner] - Uhm, excuse me, is this Seconds Left to Live?

[Owner] - I would like to adopt please.

[Clerk] - Sure! We have some animals available in the back.

[Clerk] - What type of pet are you looking for?

[Owner] - I dunno, I want a like, cute one, you know.

[Owner] - I see them all the time on my friend's Instagram (app name TBD, could be a play on words), cute pets get all the attention.

[Clerk] - Feel free to look around, I'm sure you can figure it out.

> Clerk continues scrolling on phone.

> Player gains control of Owner

> Player can walk around and interact with the animals.
> Long Dog:
[Owner] - Uhm, this one is like, a really weird shape.

[Owner] - My skin just crawled, no thank you.

[Long Dog] - I can crawl under your skin 

	[Owner] - WEIRDO!

> Persian Cat:
[Owner] - What a weird looking cow we have here.

[Persian Cat] - Your judgments are as mortal as you, they do not affect me.

[Persian Cat] - Your measly senses, dull and unrefined, can never grasp the true worth of our kind.

[Persian Cat] - We, animals, are the embodiment of perfection.

[Persian Cat] - We have walked a world far older and greater than yours.

[Persian Cat] - We were gifted by the gods.

[Persian Cat] - Ever shall you serve us, for it is your place to bow before our greatness.

[Owner] - Um, wow. You're crazy, you're done!

> German Shepherd Dog interaction:
[Owner] - Ew, why is this one so dirty!?

[German Shepherd] - YOUR VAGINA IS DIRTY, BITCH!

[German Shepherd] - I COULD SMELL THAT STANK WHEN YOU TURNED THE BLOCK!

	[Owner] - That was foul! Canceled!
	
> Pug Dog interaction:
[Owner] - Gross, look at the sag on this one, what are you, my grandma's tits!?

[Pug Dog] - POP A FUCKING XANNY, WHORE!

[Pug Dog] - GET THE FUCK OUT OF MY FACE!

	[Owner] - Excuse me?! What’s a Xanny?

> Player Cat interaction:
[Owner] - You're a cutesy one, my followers will love you!

[Player Cat] - *meows*

> When all interactions are done, a pop up above the Clerk appears (maybe an exclamation mark or something TBD).

> Player walks up to the Clerk and interacts with her.

> Player loses control of Owner

[Clerk] - Excellent choice you've got there, you can be on your way now!

[Clerk] - Thanks for adopting and saving a life!

[Owner] - Yeah, whatever, thanks! I'm heading home now.

[Owner] - Goodbye.

> Player Cat is put into cat carrier

> Owner picks up cat carrier

> Player regains control of Owner

> Owner can continue exploring

> Owner walks to the door to exit the shelter
